[package]
name = "ipfs_messages"
version = "0.1.0"
edition = "2021"

# default-run = "ecdsa-example"

[dependencies]
prost = "0.12"
prost-derive = "0.12"
prost-types = "0.12"

[build-dependencies]
prost-build = { version = "0.12" }